### ISSUE TITLE
Error "ld: symbol(s) not found for architecture x86_64" on OS X

### ISSUE THREAD

**Issue by don-prog** [madf/jwtxx#22] opened 2017-08-02 19:32 UTC
I'm trying to build my project on Hackintosh with Qt using your library, but get an issue.
I built it using these steps:

1. `cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DCMAKE_OSX_ARCHITECTURES=x86_64 ..`
2. `make`
3. `make install`
Everything was fine, but now when I trying to build my project with your lib using this in `.pro` file:
```
LIBS += -L/usr/local/lib/  -ljwtxx -ljansson -lcrypto
INCLUDEPATH += /usr/local/include/
```
I get this compile time error:
```
Undefined symbols for architecture x86_64:
  "_EVP_DigestSignFinal", referenced from:
      JWTXX::Keys::HMAC::sign(void const*, unsigned long) const in libjwtxx.a(jwt.cpp.o)
      JWTXX::Keys::PEM::sign(void const*, unsigned long) const in libjwtxx.a(jwt.cpp.o)
  "_EVP_DigestSignInit", referenced from:
      JWTXX::Keys::HMAC::sign(void const*, unsigned long) const in libjwtxx.a(jwt.cpp.o)
      JWTXX::Keys::PEM::sign(void const*, unsigned long) const in libjwtxx.a(jwt.cpp.o)
  "_EVP_DigestVerifyFinal", referenced from:
      JWTXX::Keys::PEM::verify(void const*, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libjwtxx.a(jwt.cpp.o)
  "_EVP_DigestVerifyInit", referenced from:
      JWTXX::Keys::PEM::verify(void const*, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libjwtxx.a(jwt.cpp.o)
  "_EVP_PKEY_new_mac_key", referenced from:
      JWTXX::Keys::HMAC::sign(void const*, unsigned long) const in libjwtxx.a(jwt.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**So, how can I fix it and build my project with your library?**

**Comment by madf** [comment] 2017-08-03 06:27
On OSX instead of /usr/local use /opt/local.

**Comment by don-prog** [comment] 2017-08-03 22:13
Are you sure? Because I can find `libjwtxx.a` in the /usr/local/lib. Anyway, I tried what you suggested, and even more:  `LIBS += -L/usr/local/lib/ -L/usr/opt/lib/ -ljwtxx -ljansson -lcrypto` and got the same error. Also, I checked /opt/ folder, it has only `X11` subdirectory.

**Comment by madf** [comment] 2017-08-04 07:43
The problem is that it picks system openssl which lacks EVP_ functions. Use the following:
`LIBS += -L/usr/local/opt/openssl/lib -ljwtxx -ljansson -lcrypto`

**Comment by madf** [comment] 2017-08-21 06:52
Did it help?

**Comment by yuriyvolkov** [comment] 2017-08-29 15:08
@madf had the same issue on OSX when running `make tests`. 

Reconfiguring with `cmake .. -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2k -DCMAKE_OSX_ARCHITECTURES=x86_64` fixed it. OpenSSL is installed via `brew`.

**Comment by cavernec** [comment] 2017-09-11 04:30
> The problem is that it picks system openssl which lacks EVP_ functions. Use the following:
LIBS += -L/usr/local/opt/openssl/lib -ljwtxx -ljansson -lcrypto

Worked like a charm on my side (ubuntu, not osx), thanks !

**Comment by madf** [comment] 2018-03-31 09:20
Ok, it seems I've finally fixed the issue with Homebrew and OpenSSL. Works on my Mac with MacPorts and on Travis. Closing the issue.

**Closed** 2018-03-31 09:21 UTC
